 CREATE TABLE USER(
 	ID INT PRIMARY KEY auto_increment, 
 	NAME VARCHAR(255) NOT NULL,
 	EMAIL VARCHAR(255) NOT NULL UNIQUE,
 	PASSWORD VARCHAR(255) NOT NULL
 );
 
 CREATE TABLE ADVERTISEMENT(
 	ID INT PRIMARY KEY auto_increment, 
 	CREATE_DATE DATE NOT NULL,
 	TITLE VARCHAR(100) NOT NULL,
 	TEXT CLOB NOT NULL,
 	USER_ID INT NOT NULL,
 	FOREIGN KEY(USER_ID) REFERENCES USER(ID)
 );